Improves compatibility among different C compilers. (digit separator)
The numeric literal digit separator (') is a feature of C++14, but not of C89/C99/C11. So I change to improve compatibility.

msf_gif.h: In function ‘msf_gif_begin’:
msf_gif.h:563:31: warning: multi-character character constant [-Wmultichar]
  563 |     const int MAX_PIXELS = 268'435'456; //2^30 / 4 = 1GB / bytesPerPixel
      |                               ^~~~~
msf_gif.h:563:31: error: expected ‘,’ or ‘;’ before '\x343335'